name: Scheduled Run

on:
  schedule:
    - cron: '0 */8 * * *'  # 每8小时运行一次

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Run Application
      run: java -jar target/ghosts-1.0-SNAPSHOT.jar

    - name: Commit changes
      run: |
        git config --local user.name "xinrui.an"
        git config --local user.email "xinrui.an@lkcoffee.com"
        git add README.md
        git commit -m "chore: auto update README.md with latest changes" || exit 0
        git push 